# UNIX Makefile for ELEMS

include ../makeinc.gcc

# mainClara2.hh
#CFLAGS += -I$INSTDIR/source/include
#LDFLAGS += -L$INSTDIR/lib
#LDFLAGS += -lclara2

TARGETS = gpt$(EXEEXT)
all: $(TARGETS)

include makefile.ele
ELEMOBJSO = $(ELEMOBJS:.obj=.o)

CFLAGS += -I../kernel -I. -I/home/debus/clara2/src -I/home/debus/clara2/src/include -fopenmp -Wno-write-strings

gps.c: elemlist
	../kernel/makeelems ../kernel/elemkrnl elemlist
	@echo Please rerun make.

gpt: gps.o $(ELEMOBJSO) ../kernel/elems.a ../kernel/gps.a ../kernel/gdf.a ../kernel/utils.a
	$(CXX) $(TARGET_ARCH) -o $@ gps.o $(ELEMOBJSO) /home/debus/clara2/src/mainClara2.o /home/debus/clara2/src/include/detector_dft.o $(LDFLAGS) $(CPPFLAGS) -lpthread ../kernel/elems.a ../kernel/gps.a ../kernel/gdf.a ../kernel/utils.a
	$(CP) gpt ../bin

clean:
	$(RM) gpt $(ELEMOBJSO) gps.c
